apiVersion: v1
kind: Service
metadata:
  name: my-hello-echo-app
spec:
  selector:
    app: my-hello-echo-app-pod
  ports:
  - port: 15000
    targetPort: 15000
    protocol: TCP
  type: LoadBalancer
